name: dart_port_audio
version: 0.0.1
description: >-
  Port audio library bindings for Dart 

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.9.0
  ffi: ^2.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0